apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-app-python.fullname" . }}
  labels:
    {{- include "helm-app-python.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}