name: reviewdog
on: [pull_request]
jobs:
  checkstyle:
    name: Linter for Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.LINTER_TOKEN }}
          reporter: github-pr-review
          level: warning